### ISSUE TITLE
Use Tidyverse instead of base R

### ISSUE THREAD

**Issue by DrAndiLowe** [cms-opendata-education/cms-rmaterial-multiple-languages#3]
Hi Achintya,

0. The _zeroth_ reason for opening an issue is that I want to encourage reproducible research, and a notable benefit of making the code, paper, and/or data for analysis available on GitHub is that readers of a published work can address their questions to the author(s) directly by opening an issue rather than sending them an email. The consequence of this is that the knowledge exchange happens in the open and is coupled to the work in question, rather then a private email thread in someone's inbox. This means that others can benefit from the knowledge exchange. The FAQ writes itself!

1. I like that you gave a quick introduction to R, but with time I've become increasingly convinced that it is better start teaching the tidyverse before base R. In my own teaching materials I started with base R before introducing the tidyverse, but I now think that this approach is backwards. It's like learning C before learning C++, which is how I was taught C++ (it could be argued that this approach is actually counterproductive). The tidyverse enables students to do powerful things quickly, and there is the added "wow factor" that will encourage adoption. See here for more discussion on this: [Teach the tidyverse to beginners](http://varianceexplained.org/r/teach-tidyverse/)

2. I've found knitr and rmarkdown incredible useful for producing elegantly formatted and cross-referenced documents that are immediately fit for journal submission. Can you provide any recipes for doing this from a Jupyter notebook? Is there anything as nice as knitr for Jupyter notebooks? Ideally, I want the Jupyter notebook to be the source of the published document; readers can then visit the Binder-powered repo to reproduce the work themselves. This is simpler than providing the Rmd or ipynb and instructing the reader to install a bunch of software, and doesn't ensure replication of the execution environment.

**Comment by RaoOfPhysics** [comment]
Hey @andrewjohnlowe,

0. 🙌 Completely agree!

1. You don't have to convince me that we should teach tidyverse to beginners. However, I'm not sure the objective of this repo was necessarily to teach R using particle physics but to show that CMS Open Data can also be analysed using R if needed, and to show that one doesn't need to download and install software to take a poke around these data. :) @edithvillegas did a wonderful job of preparing the original PDF, I merely converted it to a notebook for Binder-driven interactivity. Unfortunately, I don't have the time right now to re-write it to use tidyverse instead of base R, but if you have some pointers for what needs to be changed, I can return to this and make the changes you propose.

2. You can probably try https://github.com/jupyter/nbconvert for formatting the notebooks into something else. I've not had the most success with them, but then I'm not the most proficient with these tools. Maybe it's possible to install it using the `requirements.txt` file and use it in the notebook itself to build other files? Not sure. FWIW, I used https://github.com/nteract/nteract to convert the EN notebook to PDF. If you're interested in replication of the execution environment (and if installing Docker isn't a barrier -- it's only once piece of software rather than several + libraries), maybe check out this workflow to see if it makes sense: https://github.com/RaoOfPhysics/rocker-fun Also, it is possible to use RStudio through Binder as well: https://github.com/binder-examples/dockerfile-rstudio Pinging @betatim, in case he has some wisdom I've left out.

**Comment by DrAndiLowe** [comment]
1. With regards to analysis Open Data with R: is it not the case that most of this data is in ROOT format? For converting from ROOT to R data.frames, I use [RootTreeToR](https://github.com/lyonsquark/RootTreeToR). Sadly, this is no longer maintained, and I have no idea if this works with recent versions of ROOT. Moreover, the user must have ROOT installed and have launched R from an environment in which the ROOT_SYS environment variable is defined. However, [uproot](https://github.com/scikit-hep/uproot) is a very exciting development because it enables users to do ROOT I/O in pure Python and Numpy. It's possible to run a Python code chunk in an R workflow, either in the Rmd or using rPython or similar, that reads the ROOT file and outputs the data in Feather format on disk. A subsequent R code chunk can then read the Feather file and convert it to an R data.frame for downstream use. Therefore, it's possible to perform an analysis in R that uses ROOT data without producing a CSV as an intermediate data processing step. If I have time, I'll send a PR with this example using tidyverse stuff.

2. I don't have a lot of expertise with Python, and I haven't invested the time to investigate whether there are methods available to the Python user that rival knitr for R users. Definitely interested in this. I've seen RStudio running through Binder; I think this is great, but I think in most cases it's better to offer readers a simple interface for regenerating an analysis instead of the full RStudio UI, so Jupyter is probably the better option.

**Comment by RaoOfPhysics** [comment]
Thanks, @andrewjohnlowe!

1. In this example, we rely on simple CSV files from a "derived" dataset. So, there's no need to install or play with ROOT to run a simple analysis with these datasets. The objective of these data are mainly for use in an educational context. That said, if you are able to replace the analysis (and intro) shown in this repo with tidyverse tools, that would be swell! :)

2. Diffing in Jupyter (and subsequently on notebooks in GitHub) is not trivial, sadly. :/ That's my biggest pain point.

**Comment by DrAndiLowe** [comment]
1.
```{r}
install.packages("tidyverse")
require(tidyverse, quietly = TRUE)
read_csv("http://opendata.cern.ch/record/545/files/Jpsimumu.csv") %>% 
  mutate(ptotal = sqrt((px1+px2)^2 + (py1+py2)^2 + (pz1+pz2)^2), 
         E = E1+E2, 
         mass = sqrt(E^2 - ptotal^2)) %>% 
  ggplot(aes(mass)) + 
  geom_histogram(bins = 500, fill = "slateblue") + 
  xlab(expression(paste("Mass (GeV/", c^{2}, ")"))) + 
  ylab("Frequency") + 
  ggtitle("Invariant Mass Histogram") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```
This is a complete recipe that includes package installation and retrieving the data. R is concise! After tidyverse is loaded, the workflow is a single pipeline and no intermediate data objects are created.

2. Indeed.

**Comment by RaoOfPhysics** [comment]
Thanks, @andrewjohnlowe! I tried it with Binder by adding `tidyverse` to the Dockerfile and it works like a charm! I did have to make some changes to the code, though, to avoid warnings and column guesses (see https://github.com/tidyverse/readr/issues/530):

```R
require(tidyverse, warn.conflicts = FALSE)
read_csv("http://opendata.cern.ch/record/545/files/Jpsimumu.csv", col_types = cols()) %>% 
  mutate(ptotal = sqrt((px1+px2)^2 + (py1+py2)^2 + (pz1+pz2)^2), 
         E = E1+E2, 
         mass = sqrt(E^2 - ptotal^2)) %>% 
  ggplot(aes(mass)) + 
  geom_histogram(bins = 500, fill = "slateblue") + 
  xlab(expression(paste("Mass (GeV/", c^{2}, ")"))) + 
  ylab("Frequency") + 
  ggtitle("Invariant Mass Histogram") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

Will update the notebook + PDF and submit a PR. :)

**Comment by RaoOfPhysics** [comment]
Weird. `> require(tidyverse, quietly = TRUE)` didn't work in Binder and spat out the warning messages, while `> require(tidyverse, warn.conflicts = FALSE)` doesn't work in Jupyter on my machine and gives me all the same warnings. Can one use both together?

EDIT: OK, this is because of the packages I have installed locally vs packages installed via Docker for Binder. Makes sense. It's also possible to leave both in the function, so I'll keep them. See: https://stat.ethz.ch/R-manual/R-devel/library/base/html/library.html

**Comment by RaoOfPhysics** [comment]
Argh, no, that had to do with the fact that the kernel wasn't being reloaded. :/
